// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lwITHjZIWtWK8TAlid104yt8cAmRrOU',
    appId: '1:236126728561:web:777f7f92d8ed6a5b7e86d0',
    messagingSenderId: '236126728561',
    projectId: 'commit-b9e29',
    authDomain: 'commit-b9e29.firebaseapp.com',
    storageBucket: 'commit-b9e29.appspot.com',
    measurementId: 'G-8Z10Z47T7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAknUIUUJko0czyQxInPP3EofuE07hhrMs',
    appId: '1:236126728561:android:e5c4920b3660bdac7e86d0',
    messagingSenderId: '236126728561',
    projectId: 'commit-b9e29',
    storageBucket: 'commit-b9e29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQTlw51-2s65OsYO__QLDxO24n-LcIPE',
    appId: '1:236126728561:ios:2c9eea0f3239d4877e86d0',
    messagingSenderId: '236126728561',
    projectId: 'commit-b9e29',
    storageBucket: 'commit-b9e29.appspot.com',
    androidClientId:
        '236126728561-di5nur639q56s5t9col0rjka8fhvc4ak.apps.googleusercontent.com',
    iosClientId:
        '236126728561-ng6risrl2opjsk5n2vvbs5i66athu4tv.apps.googleusercontent.com',
    iosBundleId: 'com.j0ost.commit',
  );
}
